language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable

    - env: TARGET=thumbv6m-none-eabi
      rust: stable
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7m-none-eabi
      rust: stable
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7em-none-eabi
      rust: stable
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7em-none-eabihf
      rust: stable
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    - env: TARGET=thumbv6m-none-eabi
      rust: nightly
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7m-none-eabi
      rust: nightly
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7em-none-eabi
      rust: nightly
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7em-none-eabihf
      rust: nightly
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    # MSRV
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: 1.32.0

    - env: TARGET=thumbv6m-none-eabi
      rust: 1.32.0
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7m-none-eabi
      rust: 1.32.0
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7em-none-eabi
      rust: 1.32.0
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7em-none-eabihf
      rust: 1.32.0
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_success:
  - bash ci/after-success.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
