on:
  pull_request:
  merge_group:
  workflow_dispatch:

name: Clippy check
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.85
        with:
          components: clippy
      - run: cargo clippy --all --features cortex-m/critical-section-single-core -- -D warnings
      - uses: dtolnay/rust-toolchain@1.85
        with:
          components: clippy
          targets: thumbv7em-none-eabihf
      - run: cd testsuite && cargo clippy --features qemu -- -D warnings
