on:
  pull_request:
  merge_group:
  # allows manual triggering
  workflow_dispatch:

name: cortex-m on-target tests

jobs:

  hil-qemu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install qemu-run
        uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: qemu-run
      - name: Install QEMU Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libpixman-1-0 libfdt1 libglib2.0-0t64
      - name: Install custom QEMU into /opt
        run: |
          curl -sSL https://github.com/jonathanpallant/qemu9-for-ubuntu-2404/releases/download/qemu-9.2.3%2Bbuild0/qemu-9.2.3-ubuntu-24.04.tar.gz | sudo tar xvzf - -C /
          echo "/opt/qemu/bin" >> "$GITHUB_PATH"
      - name: Install toolchains
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf, thumbv6m-none-eabi
      - name: Run testsuite Cortex-M3
        run: |
          cd testsuite && cargo test --features qemu --target thumbv7em-none-eabihf
      - name: Run testsuite Cortex-M0
        run: |
          cd testsuite && cargo test --features qemu --target thumbv6m-none-eabi
